### ISSUE TITLE
Error adding data using simple encryption proxy

### ISSUE THREAD

**Issue by rmulero** [clarus-proxy/encryption-module#4]
I have started the proxy with simple encryption and, when I have tried to insert data into the database, it has given me the following SQL error:

> ERROR:  relation «T+jKI8xBObAp3» does not exist
> LINE 29: ...,'M','BCNCI','0000000001',61,'14','00000000000000000001','00...
>                                                                    ^
> ********** Error **********
> 
> ERROR: relation «T+jKI8xBObAp3» does not exist
> SQL State:42P01
> Type: 926

I guess that it has to be related with the encrypted column names, but maybe it will be good to check what happens. The policy and the SQl script I have used can be found here: [scripts.zip](https://github.com/clarus-proxy/encryption-module/files/1451305/scripts.zip)

**Comment by dieriver** [comment]
The issue raises because the Encryption Module uses the Base64 encoder to represent the encrypted bytes as a String. This encoding might use the "/" char as encoded, which poses a problem when parsing the fully qualified attribute name.
We are actually working in a naïve solution.

**Comment by dieriver** [comment]
The issue has been fixed in d397a7c1b285a01575c5a3116165ed8009e5a4a6
